# Generated by Django 5.1.7 on 2026-09-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TEACHER', 'Docente'), ('STUDENT', 'Estudiante'), ('BOT', 'Bot')], default='STUDENT', max_length=10, verbose_name='Rol de usuario'),
        ),
    ]
