# Generated by Django 5.1.7 on 2026-09-03 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En juego'), ('FINISHED', 'Finalizada'), ('ABANDONED', 'Abandonada')], default='IN_PROGRESS', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('WHITE', 'Blancas'), ('BLACK', 'Negras'), ('DRAW', 'Tablas')], max_length=10, null=True)),
                ('finish_reason', models.CharField(blank=True, choices=[('CHECKMATE', 'Jaque Mate'), ('STALEMATE', 'Tablas por Ahogado'), ('TIMEOUT', 'Tiempo Agotado'), ('RESIGNATION', 'Abandono'), ('AGREEMENT', 'Mutuo Acuerdo'), ('DRAW_RULES', 'Tablas por Regla (50 jugadas/Repetición/Insuficiencia)'), ('INSUFFICIENT_MATERIAL', 'Material Insuficiente'), ('REPETITION', 'Repetición de Posición')], max_length=30, null=True)),
                ('fen_current', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('pgn_history', models.TextField(blank=True, default='')),
                ('time_control_minutes', models.IntegerField(default=10)),
                ('time_control_increment', models.IntegerField(default=0)),
                ('white_time_left_ms', models.IntegerField(default=600000)),
                ('black_time_left_ms', models.IntegerField(default=600000)),
                ('last_move_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('turn', models.CharField(choices=[('WHITE', 'Blancas'), ('BLACK', 'Negras')], default='WHITE', max_length=5)),
                ('is_competitive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_control_minutes', models.IntegerField(default=10)),
                ('time_control_increment', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('DECLINED', 'Rechazado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenges', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_challenge', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.PositiveIntegerField()),
                ('uci', models.CharField(max_length=10)),
                ('san', models.CharField(max_length=15)),
                ('fen_after', models.CharField(max_length=100)),
                ('time_spent_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ply'],
            },
        ),
    ]
