# Generated by Django 5.1.7 on 2026-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_globalchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating_processed',
            field=models.BooleanField(default=False),
        ),
    ]
