# Generated by Django 5.1.7 on 2026-09-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_rating_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vs_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
