# Generated by Django 5.1.7 on 2026-09-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_vs_bot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
