# Generated by Django 5.1.7 on 2026-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_takebacks',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Límite máximo de deshacer jugadas'),
        ),
        migrations.AddField(
            model_name='game',
            name='takebacks_left',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Deshacer jugadas restantes'),
        ),
    ]
