# Generated by Django 5.1.7 on 2026-09-04 11:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Curso'), ('COMPLETED', 'Cerrada')], default='PENDING', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('WHITE_WIN', 'Ganan Blancas'), ('BLACK_WIN', 'Ganan Negras'), ('DRAW', 'Tablas'), ('DOUBLE_FORFEIT', 'Doble Ausencia'), ('BYE', 'Bye (Descanso)')], default='PENDING', max_length=20)),
                ('is_bye', models.BooleanField(default=False)),
                ('white_absent', models.BooleanField(default=False, verbose_name='Ausencia de Blancas')),
                ('black_absent', models.BooleanField(default=False, verbose_name='Ausencia de Negras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_pairings_as_black', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_pairing', to='games.game')),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_pairings_as_white', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='tournaments.round')),
            ],
            options={
                'ordering': ['board_number'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Torneo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('format', models.CharField(choices=[('ROUND_ROBIN', 'Todos contra Todos'), ('SWISS', 'Sistema Suizo')], default='ROUND_ROBIN', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REGISTRATION_OPEN', 'Inscripción Abierta'), ('IN_PROGRESS', 'En Curso'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('rounds_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Rondas')),
                ('time_control_minutes', models.IntegerField(default=15)),
                ('time_control_increment', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('organizers', models.ManyToManyField(blank=True, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'number')},
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Inscrito'), ('WITHDRAWN', 'Retirado'), ('DISQUALIFIED', 'Descalificado')], default='REGISTERED', max_length=15)),
                ('seed_rating', models.IntegerField(default=1200)),
                ('had_bye', models.BooleanField(default=False, verbose_name='Ya recibió un bye')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-seed_rating', 'user__username'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
