# Generated by Django 5.1.7 on 2026-09-04 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Instrucción')),
                ('initial_fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100, verbose_name='FEN Inicial')),
                ('side_to_move', models.CharField(choices=[('WHITE', 'Blancas'), ('BLACK', 'Negras')], default='WHITE', max_length=10)),
                ('category', models.CharField(choices=[('TACTICS', 'Táctica'), ('CALCULATION', 'Cálculo'), ('STRATEGY', 'Estrategia'), ('OPENINGS', 'Aperturas'), ('MIDDLEGAME', 'Medio Juego'), ('ENDGAME', 'Finales'), ('DEFENSE', 'Defensa'), ('ATTACK', 'Ataque')], default='TACTICS', max_length=20)),
                ('theme', models.CharField(choices=[('FORK', 'Doble / Horquilla'), ('PIN', 'Clavada'), ('SKEWER', 'Ataque a la Descubierta / Enfilada'), ('MATE', 'Jaque Mate'), ('OPPOSITION', 'Oposición'), ('PAWN_ENDGAME', 'Final de Peones'), ('ROOK_ENDGAME', 'Final de Torres'), ('MINOR_PIECES_ENDGAME', 'Final de Piezas Menores'), ('OPENING_REPERTOIRE', 'Repertorio de Apertura'), ('DEFENSIVE_RESOURCE', 'Recurso Defensivo'), ('BEST_CONTINUATION', 'Mejor Continuación'), ('POSITION_RECOGNITION', 'Reconocimiento Posicional')], default='FORK', max_length=30)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Principiante (1000)'), ('INTERMEDIATE', 'Intermedio (1400)'), ('ADVANCED', 'Avanzado (1800)'), ('MASTER', 'Maestro (2200+)')], default='BEGINNER', max_length=20)),
                ('objective', models.CharField(choices=[('FIND_MOVE', 'Encontrar una Jugada'), ('FIND_SEQUENCE', 'Encontrar una Secuencia'), ('WIN', 'Ganar la Posición'), ('DRAW', 'Conseguir Tablas'), ('DEFEND', 'Defender la Posición'), ('BEST_CONTINUATION', 'Encontrar la Mejor Continuación'), ('RECOGNIZE_IDEA', 'Reconocer una Idea'), ('PRACTICE_OPENING', 'Practicar una Apertura'), ('PRACTICE_ENDGAME', 'Practicar un Final')], default='WIN', max_length=30)),
                ('solution_moves', models.JSONField(default=list, verbose_name='Secuencia Solución (UCI)')),
                ('variations_json', models.JSONField(blank=True, default=dict, verbose_name='Variantes Aceptadas')),
                ('hints', models.JSONField(blank=True, default=list, verbose_name='Pistas de Ayuda')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], default='PUBLISHED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('attempts_count', models.PositiveIntegerField(default=1)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='training.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrainingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TACTICS', 'Táctica'), ('CALCULATION', 'Cálculo'), ('STRATEGY', 'Estrategia'), ('OPENINGS', 'Aperturas'), ('MIDDLEGAME', 'Medio Juego'), ('ENDGAME', 'Finales'), ('DEFENSE', 'Defensa'), ('ATTACK', 'Ataque')], max_length=20)),
                ('theme', models.CharField(choices=[('FORK', 'Doble / Horquilla'), ('PIN', 'Clavada'), ('SKEWER', 'Ataque a la Descubierta / Enfilada'), ('MATE', 'Jaque Mate'), ('OPPOSITION', 'Oposición'), ('PAWN_ENDGAME', 'Final de Peones'), ('ROOK_ENDGAME', 'Final de Torres'), ('MINOR_PIECES_ENDGAME', 'Final de Piezas Menores'), ('OPENING_REPERTOIRE', 'Repertorio de Apertura'), ('DEFENSIVE_RESOURCE', 'Recurso Defensivo'), ('BEST_CONTINUATION', 'Mejor Continuación'), ('POSITION_RECOGNITION', 'Reconocimiento Posicional')], max_length=30)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('successful_attempts', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'theme')},
            },
        ),
    ]
