# Generated by Django 5.1.7 on 2026-09-04 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_puzzles', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Moderación / Motivo de Rechazo'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En Revisión'), ('PUBLISHED', 'Publicado'), ('REJECTED', 'Rechazado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=15),
        ),
        migrations.CreateModel(
            name='PuzzleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='training.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_puzzles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'puzzle')},
            },
        ),
        migrations.CreateModel(
            name='PuzzleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Valoración (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='training.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'puzzle')},
            },
        ),
    ]
