# Generated by Django 5.1.7 on 2026-09-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_puzzle_moderated_by_puzzle_moderation_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='solution_moves',
            field=models.JSONField(blank=True, default=list, verbose_name='Secuencia Solución (UCI)'),
        ),
    ]
