# Generated by Django 5.1.7 on 2026-09-08 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botprofile_visual_delay_ms'),
        ('training', '0003_alter_puzzle_solution_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='allow_bot_opponent',
            field=models.BooleanField(default=False, verbose_name='Bot como rival'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='bot_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles_as_opponent', to='bots.bot', verbose_name='Bot contrario'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='bot_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles', to='bots.botprofile', verbose_name='Perfil del bot'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='bot_side',
            field=models.CharField(choices=[('WHITE', 'Blancas'), ('BLACK', 'Negras')], default='BLACK', max_length=10, verbose_name='Lado del bot'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='max_moves',
            field=models.PositiveIntegerField(default=0, help_text='0 = sin límite. El problema termina al alcanzar el objetivo o agotar las jugadas.', verbose_name='Máximo de jugadas'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='objective',
            field=models.CharField(choices=[('FIND_MOVE', 'Encontrar una Jugada'), ('FIND_SEQUENCE', 'Encontrar una Secuencia'), ('WIN', 'Ganar la Posición'), ('DRAW', 'Conseguir Tablas'), ('DEFEND', 'Defender la Posición'), ('BEST_CONTINUATION', 'Encontrar la Mejor Continuación'), ('RECOGNIZE_IDEA', 'Reconocer una Idea'), ('PRACTICE_OPENING', 'Practicar una Apertura'), ('PRACTICE_ENDGAME', 'Practicar un Final'), ('PLAY_VS_BOT', 'Jugar contra Bot hasta Objetivo')], default='WIN', max_length=30),
        ),
    ]
