# Generated by Django 5.1.7 on 2026-09-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_puzzle_bot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='critical_pieces',
            field=models.JSONField(blank=True, default=list, help_text='Ej: WR (torre blanca), BQ (dama negra), BK (rey negro). Si el rival captura una pieza crítica, el problema falla.', verbose_name='Piezas críticas'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='objective_type',
            field=models.CharField(blank=True, choices=[('CHECKMATE', 'Dar jaque mate')], max_length=20, null=True, verbose_name='Objetivo (problema por objetivo)'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_type',
            field=models.CharField(choices=[('SEQUENCE', 'Encontrar la solución'), ('OBJECTIVE', 'Cumplir un objetivo')], default='SEQUENCE', max_length=15, verbose_name='Tipo de problema'),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='end_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de finalización'),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='human_moves_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de jugadas realizadas por el estudiante.'),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='movelog',
            field=models.JSONField(blank=True, default=list, help_text='Jugadas UCI completas del intento (humanas y del defensor), en orden.'),
        ),
        migrations.AddField(
            model_name='puzzleattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('ABANDONED', 'Abandonado')], default='IN_PROGRESS', max_length=15),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='bot_side',
            field=models.CharField(choices=[('WHITE', 'Blancas'), ('BLACK', 'Negras')], default='BLACK', max_length=10, verbose_name='Color del bot'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='max_moves',
            field=models.PositiveIntegerField(default=50, help_text='0 = sin límite. El problema termina al alcanzar el objetivo o agotar las jugadas del estudiante.', verbose_name='Máximo de jugadas del estudiante'),
        ),
    ]
