# Generated by Django 5.1.7 on 2026-09-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_puzzle_critical_pieces_puzzle_objective_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='objective_type',
            field=models.CharField(blank=True, choices=[('CHECKMATE', 'Dar jaque mate'), ('PLAY_VS_BOT', 'Jugar contra Bot hasta Objetivo')], max_length=20, null=True, verbose_name='Objetivo (problema por objetivo)'),
        ),
    ]
