# Generated by Django 5.1.7 on 2026-09-04 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(db_index=True, max_length=200, unique=True)),
                ('score_cp', models.IntegerField(blank=True, null=True)),
                ('mate_in', models.IntegerField(blank=True, null=True)),
                ('best_move_uci', models.CharField(blank=True, max_length=10, null=True)),
                ('best_move_san', models.CharField(blank=True, max_length=20, null=True)),
                ('pv_san', models.JSONField(default=list)),
                ('depth', models.IntegerField(default=15)),
                ('engine_name', models.CharField(default='Stockfish', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pgn_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'En Proceso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('target_depth', models.IntegerField(default=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.IntegerField()),
                ('move_san', models.CharField(max_length=20)),
                ('move_uci', models.CharField(max_length=10)),
                ('fen_before', models.CharField(max_length=200)),
                ('fen_after', models.CharField(max_length=200)),
                ('score_cp', models.IntegerField(blank=True, null=True)),
                ('mate_in', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(choices=[('BEST', 'Mejor Movimiento'), ('GOOD', 'Buen Movimiento'), ('INACCURACY', 'Inexactitud'), ('MISTAKE', 'Error'), ('BLUNDER', 'Gran Error')], default='GOOD', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_analyses', to='analysis.analysisjob')),
                ('position_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.positionanalysis')),
            ],
            options={
                'ordering': ['ply'],
            },
        ),
    ]
