# Generated by Django 5.1.7 on 2026-09-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='accuracy_black',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='accuracy_white',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='estimated_elo_black',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='estimated_elo_white',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='summary_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='review_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='moveanalysis',
            name='quality',
            field=models.CharField(choices=[('BOOK', 'Teoría / Libro'), ('BRILLIANT', 'Brillante'), ('BEST', 'Mejor Movimiento'), ('EXCELLENT', 'Excelente'), ('GOOD', 'Buen Movimiento'), ('INACCURACY', 'Inexactitud'), ('MISTAKE', 'Error'), ('BLUNDER', 'Gran Error'), ('MISS', 'Oportunidad Perdida')], default='GOOD', max_length=20),
        ),
    ]
