# Generated by Django 5.1.7 on 2026-09-04 01:14

import apps.classrooms.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0003_alter_puzzle_solution_moves'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('puzzles', models.ManyToManyField(blank=True, related_name='activities', to='training.puzzle')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_type', models.CharField(choices=[('SOLVE_PUZZLES', 'Resolver Problemas'), ('PLAY_GAMES', 'Jugar Partidas'), ('ANALYZE_GAME', 'Analizar una Partida'), ('CREATE_PUZZLE', 'Crear un Problema')], max_length=20)),
                ('target_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad Objetivo')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='classrooms.activity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Aula')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('join_code', models.CharField(default=apps.classrooms.models._generate_join_code, max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aula Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classrooms', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='classrooms.classroom'),
        ),
        migrations.CreateModel(
            name='ClassroomInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('DECLINED', 'Rechazada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='classrooms.classroom')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_classroom_invitations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classrooms.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'student')},
            },
        ),
    ]
