# Generated by Django 5.1.7 on 2026-09-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_game_rating_processed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_username', models.CharField(max_length=150, verbose_name='Rival (nombre)')),
                ('opponent_rating', models.IntegerField(verbose_name='ELO del rival')),
                ('game_mode', models.CharField(choices=[('TOURNAMENT', 'Torneo'), ('CHALLENGE', 'Desafío'), ('COMPETITIVE', 'Competitiva')], max_length=15)),
                ('rating_before', models.IntegerField(verbose_name='ELO anterior')),
                ('rating_after', models.IntegerField(verbose_name='ELO nuevo')),
                ('change', models.IntegerField(verbose_name='Variación')),
                ('result', models.CharField(choices=[('WIN', 'Victoria'), ('DRAW', 'Empate'), ('LOSS', 'Derrota')], max_length=5)),
                ('k_factor', models.IntegerField(verbose_name='Factor K aplicado')),
                ('expected_score', models.FloatField(verbose_name='Puntaje esperado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes', to='games.game')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes_against', to=settings.AUTH_USER_MODEL, verbose_name='Rival')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Cambio de ELO',
                'verbose_name_plural': 'Cambios de ELO',
                'ordering': ['created_at'],
                'unique_together': {('game', 'player')},
            },
        ),
    ]
