# Generated by Django 5.1.7 on 2026-09-07 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre del perfil')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('engine_depth', models.PositiveIntegerField(default=6, verbose_name='Profundidad máx.')),
                ('move_time_ms', models.PositiveIntegerField(default=600, verbose_name='Tiempo por jugada (ms)')),
                ('skill_level', models.PositiveSmallIntegerField(default=5, help_text='Stockfish Skill Level 0-20', verbose_name='Skill Level')),
                ('multipv', models.PositiveSmallIntegerField(default=3, help_text='Candidatos razonables considerados (MultiPV)', verbose_name='MultiPV')),
                ('error_probability', models.FloatField(default=0.2, help_text='Probabilidad de jugar un candidato secundario en vez del mejor (0-1)', verbose_name='Probabilidad de error')),
                ('uci_elo', models.PositiveSmallIntegerField(blank=True, help_text='Límite UCI_Elo de Stockfish (1320-3190). Vacío = desactivado', null=True, verbose_name='UCI Elo (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Bot',
                'verbose_name_plural': 'Perfiles de Bot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=60, verbose_name='Nombre mostrado')),
                ('nickname', models.CharField(blank=True, max_length=60, verbose_name='Apodo')),
                ('avatar', models.CharField(blank=True, default='🤖', help_text='Emoji/avatar de la primera versión (opcional)', max_length=16, verbose_name='Avatar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quote', models.CharField(blank=True, max_length=200, verbose_name='Frase')),
                ('category', models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], max_length=15, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(help_text='Posición dentro de su categoría (1 = primer rival). Define la progresión.', verbose_name='Orden')),
                ('displayed_elo', models.PositiveIntegerField(help_text='ELO mostrado: etiqueta de dificultad, NUNCA se modifica por partidas.', verbose_name='ELO mostrado')),
                ('is_active', models.BooleanField(default=True, help_text='Los bots inactivos no son seleccionables; la progresión salta al siguiente bot activo.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario interna')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='bots.botprofile', verbose_name='Perfil de fuerza')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ['category', 'order', 'pk'],
                'unique_together': {('category', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BotProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('defeated', models.BooleanField(default=False)),
                ('defeated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='bots.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Bot',
                'verbose_name_plural': 'Progresos de Bot',
                'ordering': ['user_id', 'bot__category', 'bot__order'],
                'unique_together': {('user', 'bot')},
            },
        ),
    ]
