# Generated by Django 5.1.7 on 2026-09-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='visual_delay_ms',
            field=models.PositiveIntegerField(default=800, help_text='Delay visual antes de mostrar la jugada del bot (ms). Solo afecta la UX, no el cálculo.', verbose_name='Delay visual (ms)'),
        ),
    ]
