# Generated by Django 5.1.7 on 2026-09-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botprofile_visual_delay_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Apertura')),
                ('eco', models.CharField(blank=True, max_length=10, verbose_name='Código ECO (ej. B20)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción educativa')),
                ('initial_fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100, verbose_name='Posición FEN Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apertura',
                'verbose_name_plural': 'Aperturas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='opening_mode',
            field=models.CharField(choices=[('PURE_STOCKFISH', 'Stockfish Puro'), ('SPECIFIC_OPENING', 'Apertura Determinada'), ('REPERTOIRE', 'Repertorio')], default='PURE_STOCKFISH', max_length=20, verbose_name='Modo de Apertura'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='alt_move_prob',
            field=models.FloatField(default=0.2, help_text='Probabilidad de jugar una alternativa cercana 1-50 cp (0-1)', verbose_name='Prob. Alternativa'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='best_move_prob',
            field=models.FloatField(default=0.75, help_text='Probabilidad de jugar el mejor movimiento (0-1)', verbose_name='Prob. Mejor Jugada'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='blunder_prob',
            field=models.FloatField(default=0.01, help_text='Probabilidad de cometer un error grave >150 cp acotado por max_cp_loss (0-1)', verbose_name='Prob. Error Grave'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='max_cp_loss',
            field=models.PositiveIntegerField(default=300, help_text='Pérdida máxima de centipeones permitida en cualquier error (ej. 300 = 3 peones)', verbose_name='Límite Máx. Pérdida Centipeones'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='minor_error_prob',
            field=models.FloatField(default=0.04, help_text='Probabilidad de cometer un error menor 51-150 cp (0-1)', verbose_name='Prob. Error Menor'),
        ),
        migrations.AddField(
            model_name='bot',
            name='repertoire_openings',
            field=models.ManyToManyField(blank=True, related_name='bots_repertoire', to='bots.opening', verbose_name='Repertorio de Aperturas'),
        ),
        migrations.AddField(
            model_name='bot',
            name='specific_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots_specific', to='bots.opening', verbose_name='Apertura Especificada'),
        ),
        migrations.CreateModel(
            name='OpeningLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la línea / Variante')),
                ('moves_san', models.TextField(help_text='Secuencia en notación SAN (ej. 1.e4 c5 2.Nf3 d6 3.d4 cxd4)', verbose_name='Movimientos (SAN)')),
                ('moves_uci', models.JSONField(default=list, help_text='Lista de movimientos UCI (ej. ["e2e4", "c7c5", "g1f3"])', verbose_name='Movimientos (UCI)')),
                ('bot_color', models.CharField(choices=[('ANY', 'Cualquier Color'), ('WHITE', 'Blancas'), ('BLACK', 'Negras')], default='ANY', max_length=10, verbose_name='Color asignado al Bot')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bots.opening', verbose_name='Apertura')),
            ],
            options={
                'verbose_name': 'Línea de Apertura',
                'verbose_name_plural': 'Líneas de Apertura',
                'ordering': ['opening', '-priority', 'id'],
            },
        ),
    ]
