# Generated by Django 5.1.7 on 2026-09-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_opening_bot_opening_mode_botprofile_alt_move_prob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='specific_opening',
        ),
        migrations.AddField(
            model_name='bot',
            name='specific_opening_black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots_specific_black', to='bots.opening', verbose_name='Apertura con Negras'),
        ),
        migrations.AddField(
            model_name='bot',
            name='specific_opening_white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots_specific_white', to='bots.opening', verbose_name='Apertura con Blancas'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='animation_speed_ms',
            field=models.PositiveIntegerField(default=220, help_text='Velocidad de la animación de deslizamiento de la pieza (ms). Configurable desde Admin.', verbose_name='Velocidad de Animación (ms)'),
        ),
    ]
