# Generated by Django 5.1.7 on 2026-09-04 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('games', '0001_initial'),
        ('training', '0003_alter_puzzle_solution_moves'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedGameError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen_before', models.CharField(max_length=100)),
                ('student_move_uci', models.CharField(max_length=10)),
                ('student_move_san', models.CharField(max_length=20)),
                ('best_move_uci', models.CharField(blank=True, max_length=10)),
                ('best_move_san', models.CharField(blank=True, max_length=20)),
                ('score_cp_before', models.IntegerField(blank=True, null=True)),
                ('mate_in_before', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TACTICS', 'Táctica'), ('CALCULATION', 'Cálculo'), ('STRATEGY', 'Estrategia'), ('OPENINGS', 'Aperturas'), ('MIDDLEGAME', 'Medio Juego'), ('ENDGAME', 'Finales'), ('DEFENSE', 'Defensa'), ('ATTACK', 'Ataque')], max_length=20)),
                ('theme', models.CharField(choices=[('FORK', 'Doble / Horquilla'), ('PIN', 'Clavada'), ('SKEWER', 'Ataque a la Descubierta / Enfilada'), ('MATE', 'Jaque Mate'), ('OPPOSITION', 'Oposición'), ('PAWN_ENDGAME', 'Final de Peones'), ('ROOK_ENDGAME', 'Final de Torres'), ('MINOR_PIECES_ENDGAME', 'Final de Piezas Menores'), ('OPENING_REPERTOIRE', 'Repertorio de Apertura'), ('DEFENSIVE_RESOURCE', 'Recurso Defensivo'), ('BEST_CONTINUATION', 'Mejor Continuación'), ('POSITION_RECOGNITION', 'Reconocimiento Posicional')], max_length=30)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Principiante (1000)'), ('INTERMEDIATE', 'Intermedio (1400)'), ('ADVANCED', 'Avanzado (1800)'), ('MASTER', 'Maestro (2200+)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_errors', to='games.game')),
                ('generated_puzzle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_error', to='training.puzzle')),
                ('move_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detected_error', to='analysis.moveanalysis')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
