# Generated by Django 5.1.7 on 2026-09-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_piece_set', models.CharField(default='staunton', max_length=30, verbose_name='Set de piezas predeterminado')),
                ('default_board_theme', models.CharField(default='classic', max_length=30, verbose_name='Tema de tablero predeterminado')),
                ('allow_player_customization', models.BooleanField(default=True, verbose_name='Permitir personalización visual a los jugadores')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global de Ajedrez',
                'verbose_name_plural': 'Configuración Global de Ajedrez',
            },
        ),
        migrations.CreateModel(
            name='UserAppearancePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_set', models.CharField(default='staunton', max_length=30, verbose_name='Set de piezas')),
                ('board_theme', models.CharField(default='classic', max_length=30, verbose_name='Tema de tablero')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia Visual de Jugador',
                'verbose_name_plural': 'Preferencias Visuales de Jugadores',
            },
        ),
    ]
